@API_URL = http://localhost:3500

###

POST http://localhost:3500/auth/register
Content-Type: application/json

{
    "email":"s@gmail.com",
    "name":"ssss",
    "password":"helloworld",
    "hospitalName":"ssss",
    "location":"Coimbatore",
    "phno":12345678909,
    "availablebeds":{"Beds with Oxygen":243,"ICU beds":100,"General Beds":1000},
    "dean":"logan",
    "deanno":9999999999
}


###

POST http://localhost:3500/auth/login
Content-Type: application/json

{
    "email":"s@gmail.com",
    "password":"helloworld"
}


