@API_URL = http://localhost:3500

###

POST http://localhost:3500/auth/register
Content-Type: application/json

{
    "email":"s@gmail.com",
    "name":"ssss",
    "password":"helloworld",
    "hospitalName":"ssss",
    "location":"Coimbatore",
    "phno":12345678909,
    "availablebeds":{"Beds with Oxygen":243,"ICU beds":100,"General Beds":1000},
    "dean":"logan",
    "deanno":9999999999
}


###

POST http://localhost:3500/auth/login
Content-Type: application/json

{
    "email":"s@gmail.com",
    "password":"helloworld"
}


###

POST http://localhost:3500/hospital/get/all
Content-Type: application/json

{
}


###

POST http://localhost:3500/hospital/update/beds
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InNAZ21haWwuY29tIiwiaWQiOiI2MjVkYTI3ZGExZjM5NTlhZmY2YTQxYjYiLCJpYXQiOjE2NTAzNTI0ODksImV4cCI6MTY1MDM5MjQ4OX0.MzViNEzSwRJz5LZk2TYWo-KqNrA1z0a-HGmpVGmwKug
Content-Type: application/json

{
    "availableBeds":{"beds with oxygen":2}

}
